<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title><?= $this->e($title) ?></title>
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />-->
    <style>
        body {
            text-align: center;
        }
    </style>
    <?= $this->section('css') ?>
</head>
<body>

<?= $this->section('content') ?>
<?= $this->section('js') ?>

</body>
</html>